import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "./ui/theme-wrapper";
import Header from "./ui/header";
import Footer from "./ui/footer";
import { ScrollArea } from "@/app/ui/scroll-area";
import { fontMichroma, geistMono, geistSans } from "@/public/assets/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.className} ${geistMono.variable} ${fontMichroma.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex flex-col justify-center min-h-screen px-10">
            <Header />
            <ScrollArea className="flex flex-col justify-center h-[82svh] bg-[#01100c] mt-8 items-center rounded-2xl">
              {children}
            </ScrollArea>
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
